version: "2"
services:
    www:
        image: php:5.6-apache 
        ports: 
            - "8001:80"
        volumes:
            - ../public:/var/www/html/
        networks:
            - default
volumes:
    persistent: